#!/usr/bin/php
<?php

// Use your own Pushover user Key you will find it in the home page https://pushover.net/
$userKey = "XXXXXXXXXXXXXXXXXXXX";

// Add your application token
$appToken="XXXXXXXXXXXXXXXXXXXXXX";

if ($argv[3]!=''){
	$sound = array ('pushover',
	'bike',
	'bugle',
	'cashregister',
	'classical',
	'cosmic',
	'falling',
	'gamelan',
	'incoming',
	'intermission',
	'magic',
	'mechanical',
	'pianobar',
	'siren',
	'spacealarm',
	'tugboat',
	'alien',
	'climb',
	'persistent',
	'echo',
	'updown',
	'none');
	$sound = $sound[$argv[3]];
}
else
	$sound = 'cosmic';
 
curl_setopt_array($ch = curl_init(), array(
  CURLOPT_URL => "https://api.pushover.net/1/messages.json",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_POSTFIELDS => array(
     "token" => $appToken,
     "user" => $userKey,
     "title" => $argv[1],
     "message" => $argv[2],
     "sound" => $sound,
   )));
curl_exec($ch);
curl_close($ch);

?>
